# Default values for anka-build-cloud.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

controller:
  version: '1.31.1'
  replicaCount: 2
  ANKA_ANKA_REGISTRY:
  ANKA_ETCD_ENDPOINTS: 'etcd-headless.anka-build-cloud.svc.cluster.local:2379'
  # ANKA_ETCD_ENDPOINTS: 'etcd-0.etcd-headless.anka-build-cloud.svc.cluster.local:2379,etcd-1.etcd-headless.anka-build-cloud.svc.cluster.local:2379,etcd-2.etcd-headless.anka-build-cloud.svc.cluster.local:2379'
  ANKA_LOCAL_ANKA_REGISTRY: 'http://registry.anka-build-cloud.svc.cluster.local:8089'
  ingressALBHostname: false
  ANKA_ENABLE_CENTRAL_LOGGING: true

registry:
  version: '1.31.1'
  replicaCount: 1
  volumeClaimUseEFS: false
  volumeClaimID:
  volumeClaimUseLocalStorage: false
  volumeClaimName: 'registry-data'
  volumeClaimCapacityStorageSize: 200Gi
  ingressALBHostname: false

etcd:
  enabled: true
  version: '1.31.1'
  volumeClaimUseLocalStorage: true
  volumeClaimName: 'etcd-data'
  volumeClaimCapacityStorageSize: 10Gi
  ETCD_QUOTA_BACKEND_BYTES: '6294967296'
  # nodeAffinityKey: 'topology.kubernetes.io/zone'
  # nodeAffinityValue: 'us-west-2a'
