{{ if .Values.controller.ingressALBHostname }}
---
apiVersion: v1
kind: Service
metadata:
  name: controller
spec:
  ports:
    - name: controller
      port: 80
  selector:
    app: controller
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: controller
  annotations: # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#manage-backend-security-group-rules
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    {{ if .Values.controller.ingressALBSecurityGroup }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.controller.ingressALBSecurityGroup }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    {{ end }}
    alb.ingress.kubernetes.io/tags: Name={{ .Release.Name }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ required ".controller.ingressALBHostname value is required!" .Values.controller.ingressALBHostname  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: controller
                port:
                  number: 80
{{ end }}
---
{{ if .Values.registry.ingressALBHostname }}
---
apiVersion: v1
kind: Service
metadata:
  name: registry
spec:
  ports:
    - name: registry
      port: 8089
  selector:
    app: registry
  type: NodePort
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: registry
  annotations: # https://kubernetes-sigs.github.io/aws-load-balancer-controller/v2.4/guide/ingress/annotations/#manage-backend-security-group-rules
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTP": 8089}]'
    {{ if .Values.registry.ingressALBSecurityGroup }}
    alb.ingress.kubernetes.io/security-groups: {{ .Values.registry.ingressALBSecurityGroup }}
    alb.ingress.kubernetes.io/manage-backend-security-group-rules: "true"
    {{ end }}
    alb.ingress.kubernetes.io/tags: Name={{ .Release.Name }}
spec:
  ingressClassName: alb
  rules:
    - host: {{ required ".registry.ingressALBHostname value is required!" .Values.registry.ingressALBHostname  }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: registry
                port:
                  number: 8089
{{ end }}
{{ if .Values.etcd.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: etcd-headless
spec:
  clusterIP: None
  selector:
    app: etcd
  ports:
    - protocol: TCP
      port: 2379
      targetPort: 2379
{{ end }}