---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: controller
  name: controller
spec:
  replicas: {{ .Values.controller.replicaCount }}
  selector:
    matchLabels:
      app: controller
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels: 
        app: controller
      name: controller
    spec:
      containers:
        - name: controller
          image: veertu/anka-build-cloud-controller:v{{ .Values.controller.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: ANKA_ANKA_REGISTRY
              value: {{ required ".controller.ANKA_ANKA_REGISTRY value is required!" .Values.controller.ANKA_ANKA_REGISTRY  }}
            - name: ANKA_LOCAL_ANKA_REGISTRY
              value: {{ .Values.controller.ANKA_LOCAL_ANKA_REGISTRY }}
            - name: ANKA_ETCD_ENDPOINTS
              value: {{ .Values.controller.ANKA_ETCD_ENDPOINTS }}
      restartPolicy: Always
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: registry
  name: registry
spec:
  replicas: {{ .Values.registry.replicaCount }}
  selector:
    matchLabels:
      app: registry
  strategy:
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: registry
      name: registry
    spec:
      containers:
        - name: registry
          image: veertu/anka-build-cloud-registry:v{{ .Values.registry.version }}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8089
          volumeMounts:
            - mountPath: /mnt/vol
              name: registry-data
      restartPolicy: Always
      volumes:
        - name: registry-data
          persistentVolumeClaim:
            claimName: {{ required ".registry.volumeClaimName value is required!" .Values.registry.volumeClaimName }}